//:::~ 
//:::~ File automatically generated by ctt.py  NO EDITAR
//:::~ 

#include <tclap/CmdLine.h>
#include "base.h"

//:::~ +++++++++++++++++++++++++++++++++++++++++++++++++++++++
//:::~ Definiciones de las variables seteables desde el infile
//:::~ +++++++++++++++++++++++++++++++++++++++++++++++++++++++

namespace CTGlobal
{

  std::string filein = "input.wisdom";

  int verbosityLevel  = 0;
  bool quietRun = false;
  std::string prog_name = "" ;

//:::~  information regime
std::string regime = "AGGR" ;
//:::~  strength of social influence
double alpha = 1.0 ;
//:::~  strength of individual conviction
double beta = 1.0 ;
//:::~  time step for the simulation
double deltat = 0.01 ;
//:::~  number of time steps in the simulation
long t = 300 ;
//:::~  initial estimates (fig 4 top-left) are stored here
std::string filename = "wisdom.in" ;
//:::~  number of agents
int N = 100 ;
//:::~  noise diffusion coefficient
double Dn = 0.5 ;
//:::~  the logarithm of the Truth
double lnTruth = -2.0 ;
//:::~  semilla de los numeros aleatorios
long randomseed = 0 ;

// from backends

};




//:::~ :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
//:::::::::::::: OPTION READING (BEGIN) ::::::::::::::::::::::::::::::::::::::::
//::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
//::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
//::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
void CTGlobal::initialize_program(int &argc, char** & argv){
 using namespace std;
 
 	  TCLAP::CmdLine cmd(string( " release date: ")+RELEASE_DATE, ' ', VERSION_NUMBER);

    TCLAP::ValueArg<string> nameArg("i","input","configuration input file name",false,filein,"string"); 
    cmd.add( nameArg );

    TCLAP::SwitchArg quietSwitch("q","quiet","Quietly runs the program", false);
    cmd.add( quietSwitch );

    TCLAP::MultiSwitchArg verboseMSwitch("v","verbose", "Increases verbosity level");
    cmd.add( verboseMSwitch );

 try {  
    cmd.parse( argc, argv );
    filein = nameArg.getValue();
    quietRun = quietSwitch.getValue();
    if(! quietRun) verbosityLevel = verboseMSwitch.getValue();


 } catch (TCLAP::ArgException &e) 
 { cerr << "error: " << e.error() << " for arg " << e.argId() << endl; }
 
  
  if(!quietRun) {
    std:: cerr << "\n< " << argv[0] << " > version: "<< VERSION_NUMBER  ;
    std:: cerr << " ( released on: "<< RELEASE_DATE << " )" <<  std::endl;
    std:: cerr << "< " << argv[0] << " > compiled on: "<< __DATE__  ;
    std:: cerr << " "<< __TIME__ <<  std::endl;
  }

 if(filein != "" ){
 std::fstream * sin = new std::fstream( filein.c_str() ,std::ios::in);
 
  if( !sin->fail() )
    input_variables(*sin);
  else{
    std:: cerr << "< " << argv[0] << " - ERROR > " ;
    std::cerr << "could not read input from file '" << filein << "'"  << std::endl;
    exit( EXIT_FAILURE );
  } 
} 


//::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
//::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
//::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
//:::::::::::::: OPTION READING ( END ) ::::::::::::::::::::::::::::::::::::::::
//:::~ :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
}

void CTGlobal::query_output(std::string type, std::string msg , std::string oc, int indent){
  for(int i=0;i<indent;i++) std::cerr << " ";
  std::cerr << oc[0] << " ";
  std::cerr << prog_name << " - "<< type << " ";
  std::cerr << oc[1] << " ";
  std::cerr << msg << std::endl;
}


//:::~ +++++++++++++++++++++++++++++++++++++++++++++++++++++++
//:::~ Parse de las variables
//:::~ +++++++++++++++++++++++++++++++++++++++++++++++++++++++

void CTGlobal::input_variables(std::istream &fin)
{
    
    
 std::string foo;
 fin >> foo;
 while( (!fin.eof()) &&  (foo != "end") )
 {
    
  if (  (foo !="regime") && (foo !="alpha") && (foo !="beta") && (foo !="deltat") && (foo !="t") && (foo !="filename") && (foo !="N") && (foo !="Dn") && (foo !="lnTruth") && (foo !="randomseed")  )
  {  
    std::cerr << " +  {ctt - ERROR} command " <<  foo << " not understood";
    std::cerr << std::endl;
    exit(EXIT_FAILURE);
    
    
  }  
  if (foo == "regime")
  {
    {
      fin >>  regime ;
      if (  (regime!="AGGR")&&(regime!="FULL")&&(regime!="NO") )
      {
        std::cerr << " +  {ctt - ERROR} '" << regime  << "' not between possible values of regime"  << std::endl;
        std::cerr << " +  {ctt - ERROR} Possible values are: " <<  "AGGR"<< " " <<"FULL"<< " " <<"NO"  << std::endl;
        exit(EXIT_FAILURE);
      }
    }
    std::cerr << " +  {ctt - SETTING} " << "regime = " << regime  << std::endl;

  }
  if (foo == "alpha")
  {
    fin >>  alpha ;
      std::cerr << " +  {ctt - SETTING} " << "alpha = " << alpha  << std::endl;

  }
  if (foo == "beta")
  {
    fin >>  beta ;
      std::cerr << " +  {ctt - SETTING} " << "beta = " << beta  << std::endl;

  }
  if (foo == "deltat")
  {
    fin >>  deltat ;
      std::cerr << " +  {ctt - SETTING} " << "deltat = " << deltat  << std::endl;

  }
  if (foo == "t")
  {
    fin >>  t ;
      std::cerr << " +  {ctt - SETTING} " << "t = " << t  << std::endl;

  }
  if (foo == "filename")
  {
    fin >>  filename ;
      std::cerr << " +  {ctt - SETTING} " << "filename = " << filename  << std::endl;

  }
  if (foo == "N")
  {
    fin >>  N ;
      std::cerr << " +  {ctt - SETTING} " << "N = " << N  << std::endl;

  }
  if (foo == "Dn")
  {
    fin >>  Dn ;
      std::cerr << " +  {ctt - SETTING} " << "Dn = " << Dn  << std::endl;

  }
  if (foo == "lnTruth")
  {
    fin >>  lnTruth ;
      std::cerr << " +  {ctt - SETTING} " << "lnTruth = " << lnTruth  << std::endl;

  }
  if (foo == "randomseed")
  {
    fin >>  randomseed ;
      std::cerr << " +  {ctt - SETTING} " << "randomseed = " << randomseed  << std::endl;

  }
  fin >> foo;
 }
  if(randomseed)
    rt_rand_init(randomseed);
    
  else
  {
      struct timeval tv;
     gettimeofday(&tv, NULL); 
    randomseed=tv.tv_usec;
    rt_rand_init(randomseed);
  }
  std::fstream frandom("random.seed",std::ios::app | std::ios::out );
  frandom << randomseed  << std::endl ;  
  frandom.close();  
    
}

//:::~ +++++++++++++++++++++++++++++++++++++++++++++++++++++++
//:::~ Pequegno Help
//:::~ +++++++++++++++++++++++++++++++++++++++++++++++++++++++

void CTGlobal::help_available()
{

 
   std::cerr << "regime := tipo  string "  << std::endl ;
   std::cerr << "--> information regime" << std::endl;
   std::cerr       << "    Possible values are: " <<  "AGGR"<< " " <<"FULL"<< " " <<"NO"  << std::endl ;

   std::cerr << "alpha := tipo  double "  << std::endl ;
   std::cerr << "--> strength of social influence" << std::endl;
   std::cerr << "    Valor por defecto : 1.0"  << std::endl ;

   std::cerr << "beta := tipo  double "  << std::endl ;
   std::cerr << "--> strength of individual conviction" << std::endl;
   std::cerr << "    Valor por defecto : 1.0"  << std::endl ;

   std::cerr << "deltat := tipo  double "  << std::endl ;
   std::cerr << "--> time step for the simulation" << std::endl;
   std::cerr << "    Valor por defecto : 0.01"  << std::endl ;

   std::cerr << "t := tipo  long "  << std::endl ;
   std::cerr << "--> number of time steps in the simulation" << std::endl;
   std::cerr << "    Valor por defecto : 300"  << std::endl ;

   std::cerr << "filename := tipo  string "  << std::endl ;
   std::cerr << "--> initial estimates (fig 4 top-left) are stored here" << std::endl;
   std::cerr << "    Valor por defecto : \"wisdom.in\""  << std::endl ;

   std::cerr << "N := tipo  int "  << std::endl ;
   std::cerr << "--> number of agents" << std::endl;
   std::cerr << "    Valor por defecto : 100"  << std::endl ;

   std::cerr << "Dn := tipo  double "  << std::endl ;
   std::cerr << "--> noise diffusion coefficient" << std::endl;
   std::cerr << "    Valor por defecto : 0.5"  << std::endl ;

   std::cerr << "lnTruth := tipo  double "  << std::endl ;
   std::cerr << "--> the logarithm of the Truth" << std::endl;
   std::cerr << "    Valor por defecto : -2.0"  << std::endl ;

   std::cerr << "randomseed := tipo  long "  << std::endl ;
   std::cerr << "--> semilla de los numeros aleatorios" << std::endl;
   std::cerr << "    Valor por defecto : 0"  << std::endl ;

 exit(EXIT_FAILURE);
}

