//:::~ 
//:::~ File automatically generated by ctt.py  NO EDITAR
//:::~ 

#include <tclap/CmdLine.h>
#include "base.h"

//:::~ +++++++++++++++++++++++++++++++++++++++++++++++++++++++
//:::~ Definiciones de las variables seteables desde el infile
//:::~ +++++++++++++++++++++++++++++++++++++++++++++++++++++++

namespace CTGlobal
{

  std::string filein = "input.gsplit";

  int verbosityLevel  = 0;
  bool quietRun = false;
  std::string prog_name = "" ;

//:::~  sets whether to store the dynamics
bool  store_dynamics = false ;
//:::~  file name to store the dynamics
std::string store_dynamics_filename = "dynamics.out" ;
//:::~  information regime
std::string regime = "AGGR" ;
//:::~  (c)ontrol case (no splitting) or (t)est case (splitting)
std::string control_case = "c" ;
//:::~  std of group one
double sigma1 = 1.0 ;
//:::~  std of group two
double sigma2 = 1.0 ;
//:::~  strength of social influence
double alpha = 1.0 ;
//:::~  strength of individual conviction
double beta = 1.0 ;
//:::~  time step for the simulation
double deltat = 0.01 ;
//:::~  number of time steps for interaction
int T = 300 ;
//:::~  number of agents
int N = 100 ;
//:::~  number of realizations
int M = 100 ;
//:::~  relative size of the second group
double n2 = 0.01 ;
//:::~  noise diffusion coefficient
double Dn = 0.5 ;
//:::~  semilla de los numeros aleatorios
long randomseed = 0 ;

// from backends


std::fstream *f_dynamics_out = 0;

};




//:::~ :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
//:::::::::::::: OPTION READING (BEGIN) ::::::::::::::::::::::::::::::::::::::::
//::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
//::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
//::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
void CTGlobal::initialize_program(int &argc, char** & argv){
 using namespace std;
 
 	  TCLAP::CmdLine cmd(string( " release date: ")+RELEASE_DATE, ' ', VERSION_NUMBER);

    TCLAP::ValueArg<string> nameArg("i","input","configuration input file name",false,filein,"string"); 
    cmd.add( nameArg );

    TCLAP::SwitchArg quietSwitch("q","quiet","Quietly runs the program", false);
    cmd.add( quietSwitch );

    TCLAP::MultiSwitchArg verboseMSwitch("v","verbose", "Increases verbosity level");
    cmd.add( verboseMSwitch );

 try {  
    cmd.parse( argc, argv );
    filein = nameArg.getValue();
    quietRun = quietSwitch.getValue();
    if(! quietRun) verbosityLevel = verboseMSwitch.getValue();


 } catch (TCLAP::ArgException &e) 
 { cerr << "error: " << e.error() << " for arg " << e.argId() << endl; }
 
  
  if(!quietRun) {
    std:: cerr << "\n< " << argv[0] << " > version: "<< VERSION_NUMBER  ;
    std:: cerr << " ( released on: "<< RELEASE_DATE << " )" <<  std::endl;
    std:: cerr << "< " << argv[0] << " > compiled on: "<< __DATE__  ;
    std:: cerr << " "<< __TIME__ <<  std::endl;
  }

 if(filein != "" ){
 std::fstream * sin = new std::fstream( filein.c_str() ,std::ios::in);
 
  if( !sin->fail() )
    input_variables(*sin);
  else{
    std:: cerr << "< " << argv[0] << " - ERROR > " ;
    std::cerr << "could not read input from file '" << filein << "'"  << std::endl;
    exit( EXIT_FAILURE );
  } 
} 

if(store_dynamics ){
    
    f_dynamics_out = new std::fstream (store_dynamics_filename.c_str(),std::ios::out | std::ios::app );
    if( f_dynamics_out->fail()  ) {
      std::cerr << "< " << argv[0] << " - ERROR > " ;
      std::cerr << "opening file: '" << store_dynamics_filename ;
      std::cerr << "' for output" << std::endl;
      exit(EXIT_FAILURE);
    }
}


//::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
//::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
//::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
//:::::::::::::: OPTION READING ( END ) ::::::::::::::::::::::::::::::::::::::::
//:::~ :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
}

void CTGlobal::query_output(std::string type, std::string msg , std::string oc, int indent){
  for(int i=0;i<indent;i++) std::cerr << " ";
  std::cerr << oc[0] << " ";
  std::cerr << prog_name << " - "<< type << " ";
  std::cerr << oc[1] << " ";
  std::cerr << msg << std::endl;
}


//:::~ +++++++++++++++++++++++++++++++++++++++++++++++++++++++
//:::~ Parse de las variables
//:::~ +++++++++++++++++++++++++++++++++++++++++++++++++++++++

void CTGlobal::input_variables(std::istream &fin)
{
    
    
 std::string foo;
 fin >> foo;
 while( (!fin.eof()) &&  (foo != "end") )
 {
    
  if (  (foo !="store_dynamics_filename") && (foo !="regime") && (foo !="control_case") && (foo !="sigma1") && (foo !="sigma2") && (foo !="alpha") && (foo !="beta") && (foo !="deltat") && (foo !="T") && (foo !="N") && (foo !="M") && (foo !="n2") && (foo !="Dn") && (foo !="randomseed") && (foo !="store_dynamics")  )
  {  
    std::cerr << " +  {ctt - ERROR} command " <<  foo << " not understood";
    std::cerr << std::endl;
    exit(EXIT_FAILURE);
    
    
  }  
  if (foo == "store_dynamics")
  {
      store_dynamics =true;
      std::cerr << " +  {ctt - SETTING} " << "store_dynamics = true" << std::endl;
  }
  if (foo == "store_dynamics_filename")
  {
    fin >>  store_dynamics_filename ;
      std::cerr << " +  {ctt - SETTING} " << "store_dynamics_filename = " << store_dynamics_filename  << std::endl;

  }
  if (foo == "regime")
  {
    {
      fin >>  regime ;
      if (  (regime!="AGGR")&&(regime!="FULL")&&(regime!="NO") )
      {
        std::cerr << " +  {ctt - ERROR} '" << regime  << "' not between possible values of regime"  << std::endl;
        std::cerr << " +  {ctt - ERROR} Possible values are: " <<  "AGGR"<< " " <<"FULL"<< " " <<"NO"  << std::endl;
        exit(EXIT_FAILURE);
      }
    }
    std::cerr << " +  {ctt - SETTING} " << "regime = " << regime  << std::endl;

  }
  if (foo == "control_case")
  {
    {
      fin >>  control_case ;
      if (  (control_case!="c")&&(control_case!="t") )
      {
        std::cerr << " +  {ctt - ERROR} '" << control_case  << "' not between possible values of control_case"  << std::endl;
        std::cerr << " +  {ctt - ERROR} Possible values are: " <<  "c"<< " " <<"t"  << std::endl;
        exit(EXIT_FAILURE);
      }
    }
    std::cerr << " +  {ctt - SETTING} " << "control_case = " << control_case  << std::endl;

  }
  if (foo == "sigma1")
  {
    fin >>  sigma1 ;
      std::cerr << " +  {ctt - SETTING} " << "sigma1 = " << sigma1  << std::endl;

  }
  if (foo == "sigma2")
  {
    fin >>  sigma2 ;
      std::cerr << " +  {ctt - SETTING} " << "sigma2 = " << sigma2  << std::endl;

  }
  if (foo == "alpha")
  {
    fin >>  alpha ;
      std::cerr << " +  {ctt - SETTING} " << "alpha = " << alpha  << std::endl;

  }
  if (foo == "beta")
  {
    fin >>  beta ;
      std::cerr << " +  {ctt - SETTING} " << "beta = " << beta  << std::endl;

  }
  if (foo == "deltat")
  {
    fin >>  deltat ;
      std::cerr << " +  {ctt - SETTING} " << "deltat = " << deltat  << std::endl;

  }
  if (foo == "T")
  {
    fin >>  T ;
      std::cerr << " +  {ctt - SETTING} " << "T = " << T  << std::endl;

  }
  if (foo == "N")
  {
    fin >>  N ;
      std::cerr << " +  {ctt - SETTING} " << "N = " << N  << std::endl;

  }
  if (foo == "M")
  {
    fin >>  M ;
      std::cerr << " +  {ctt - SETTING} " << "M = " << M  << std::endl;

  }
  if (foo == "n2")
  {
    fin >>  n2 ;
      std::cerr << " +  {ctt - SETTING} " << "n2 = " << n2  << std::endl;

  }
  if (foo == "Dn")
  {
    fin >>  Dn ;
      std::cerr << " +  {ctt - SETTING} " << "Dn = " << Dn  << std::endl;

  }
  if (foo == "randomseed")
  {
    fin >>  randomseed ;
      std::cerr << " +  {ctt - SETTING} " << "randomseed = " << randomseed  << std::endl;

  }
  fin >> foo;
 }
  if(randomseed)
    rt_rand_init(randomseed);
    
  else
  {
      struct timeval tv;
     gettimeofday(&tv, NULL); 
    randomseed=tv.tv_usec;
    rt_rand_init(randomseed);
  }
  std::fstream frandom("random.seed",std::ios::app | std::ios::out );
  frandom << randomseed  << std::endl ;  
  frandom.close();  
    
}

//:::~ +++++++++++++++++++++++++++++++++++++++++++++++++++++++
//:::~ Pequegno Help
//:::~ +++++++++++++++++++++++++++++++++++++++++++++++++++++++

void CTGlobal::help_available()
{

 
   std::cerr << " store_dynamics := tipo bool "  << std::endl ;
   std::cerr << "--> sets whether to store the dynamics" << std::endl;
   std::cerr << "    Valor por defecto : false" << std::endl;    std::cerr << "store_dynamics_filename := tipo  string "  << std::endl ;
   std::cerr << "--> file name to store the dynamics" << std::endl;
   std::cerr << "    Valor por defecto : \"dynamics.out\""  << std::endl ;

   std::cerr << "regime := tipo  string "  << std::endl ;
   std::cerr << "--> information regime" << std::endl;
   std::cerr       << "    Possible values are: " <<  "AGGR"<< " " <<"FULL"<< " " <<"NO"  << std::endl ;

   std::cerr << "control_case := tipo  string "  << std::endl ;
   std::cerr << "--> (c)ontrol case (no splitting) or (t)est case (splitting)" << std::endl;
   std::cerr       << "    Possible values are: " <<  "c"<< " " <<"t"  << std::endl ;

   std::cerr << "sigma1 := tipo  double "  << std::endl ;
   std::cerr << "--> std of group one" << std::endl;
   std::cerr << "    Valor por defecto : 1.0"  << std::endl ;

   std::cerr << "sigma2 := tipo  double "  << std::endl ;
   std::cerr << "--> std of group two" << std::endl;
   std::cerr << "    Valor por defecto : 1.0"  << std::endl ;

   std::cerr << "alpha := tipo  double "  << std::endl ;
   std::cerr << "--> strength of social influence" << std::endl;
   std::cerr << "    Valor por defecto : 1.0"  << std::endl ;

   std::cerr << "beta := tipo  double "  << std::endl ;
   std::cerr << "--> strength of individual conviction" << std::endl;
   std::cerr << "    Valor por defecto : 1.0"  << std::endl ;

   std::cerr << "deltat := tipo  double "  << std::endl ;
   std::cerr << "--> time step for the simulation" << std::endl;
   std::cerr << "    Valor por defecto : 0.01"  << std::endl ;

   std::cerr << "T := tipo  int "  << std::endl ;
   std::cerr << "--> number of time steps for interaction" << std::endl;
   std::cerr << "    Valor por defecto : 300"  << std::endl ;

   std::cerr << "N := tipo  int "  << std::endl ;
   std::cerr << "--> number of agents" << std::endl;
   std::cerr << "    Valor por defecto : 100"  << std::endl ;

   std::cerr << "M := tipo  int "  << std::endl ;
   std::cerr << "--> number of realizations" << std::endl;
   std::cerr << "    Valor por defecto : 100"  << std::endl ;

   std::cerr << "n2 := tipo  double "  << std::endl ;
   std::cerr << "--> relative size of the second group" << std::endl;
   std::cerr << "    Valor por defecto : 0.01"  << std::endl ;

   std::cerr << "Dn := tipo  double "  << std::endl ;
   std::cerr << "--> noise diffusion coefficient" << std::endl;
   std::cerr << "    Valor por defecto : 0.5"  << std::endl ;

   std::cerr << "randomseed := tipo  long "  << std::endl ;
   std::cerr << "--> semilla de los numeros aleatorios" << std::endl;
   std::cerr << "    Valor por defecto : 0"  << std::endl ;

 exit(EXIT_FAILURE);
}

